NeZaboravi/Controllers/ArtiklController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using NeZaboravi.Data;
using NeZaboravi.Interfaces;
using NeZaboravi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NeZaboravi.Controllers
{
    [Authorize]
    public class ArtiklController : Controller
    {
        private readonly IArtiklService _artiklService;
        private readonly IUserContextService _userContextService;

        public ArtiklController(IArtiklService artiklService, IUserContextService userContextService)
        {
            _artiklService = artiklService;
            _userContextService = userContextService;
        }

        public async Task<IActionResult> Index()
        {
            var username = _userContextService.GetCurrentUsername();
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            var artikls = await _artiklService.GetUserArtiklsAsync(username);
            return View(artikls);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var artikl = await _artiklService.GetArtiklByIdAsync(id.Value);
            if (artikl == null)
            {
                return NotFound();
            }

            return View(artikl);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Ime,Ducan")] Artikl artikl)
        {
            if (!ModelState.IsValid)
            {
                return View(artikl);
            }

            var username = _userContextService.GetCurrentUsername();
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            await _artiklService.CreateArtiklAsync(artikl, username);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var artikl = await _artiklService.GetArtiklByIdAsync(id.Value);
            if (artikl == null)
            {
                return NotFound();
            }

            return View(artikl);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ime,Ducan")] Artikl artikl)
        {
            if (id != artikl.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(artikl);
            }

            var success = await _artiklService.UpdateArtiklAsync(artikl);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var success = await _artiklService.DeleteArtiklAsync(id.Value);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

NeZaboravi/Controllers/KorisnikController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NeZaboravi.Data;
using NeZaboravi.Interfaces;
using NeZaboravi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NeZaboravi.Controllers
{
    public class KorisnikController : Controller
    {
        private readonly IKorisnikService _korisnikService;
        private readonly IUserContextService _userContextService;

        public KorisnikController(IKorisnikService korisnikService, IUserContextService userContextService)
        {
            _korisnikService = korisnikService;
            _userContextService = userContextService;
        }

        public async Task<IActionResult> Index()
        {
            var korisnici = await _korisnikService.GetAllKorisniciAsync();
            return View(korisnici);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var korisnik = await _korisnikService.GetKorisnikByIdAsync(id.Value);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Ime")] Korisnik korisnik)
        {
            if (!ModelState.IsValid)
            {
                return View(korisnik);
            }

            var username = _userContextService.GetCurrentUsername();
            if (string.IsNullOrEmpty(username))
            {
                return Unauthorized();
            }

            await _korisnikService.CreateKorisnikAsync(korisnik, username);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var korisnik = await _korisnikService.GetKorisnikByIdAsync(id.Value);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ime,Username,Username2,Username3,Username4,Username5,Username6,Username7,Username8,Username9,Username10")] Korisnik korisnik)
        {
            if (id != korisnik.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(korisnik);
            }

            var success = await _korisnikService.UpdateKorisnikAsync(korisnik);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var korisnik = await _korisnikService.GetKorisnikByIdAsync(id.Value);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var success = await _korisnikService.DeleteKorisnikAsync(id);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

NeZaboravi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NeZaboravi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NeZaboravi.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css"
          rel="stylesheet" />
</head>
<body style="background: rgb(255,255,255);
background: radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(223,255,209,1) 100%);">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ne Zaboravi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item text-center">
                            <div>
                                <i class="fas fa-home fa-lg mb-1"></i>
                            </div>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Početna</a>
                        </li>
                        <li class="nav-item text-center">
                            <div>
                                <i class="fas fa-cart-arrow-down"></i>
                            </div>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikl" asp-action="Index">Pogledaj sve stavke za kupnju</a>
                        </li>
                        <li class="nav-item text-center">
                            <div>
                                <i class="fas fa-cart-plus"></i>
                            </div>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artikl" asp-action="Create">Dodaj novu stavku za kupnju</a>
                        </li>
                        <li class="nav-item text-center">
                            <div>
                                <i class="fas fa-arrow-up"></i>
                            </div>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Korisnik" asp-action="Create">Dodaj novog korisnika da gleda artikle</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NeZaboravi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
  <!-- Bootstrap Bundle with Popper -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
    integrity="sha384-U1ji1NqdzPU3+j6RSx1oAt/KVqzczRjG1MxsZ3NGMw7g19zFhS5DbiXMEiAFUiNX"
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>